SELECT * FROM bigbasket_products
	--SANYASI NAIDU LALAM

--Discount: Calculated as (market_price - sale_price) / market_price * 100, 
--representing the percentage discount offered on the product.
SELECT
    product,
    sale_price,
    market_price,
    ((market_price - sale_price) / market_price * 100) AS discount_percentage
FROM
    bigbasket_products


-- Sales Analysis:
SELECT
    category,
    COUNT(*) AS total_products_sold,  
    -- Total number of products sold in each category
    SUM(sale_price) AS total_revenue,  
    -- Total revenue for each category
    AVG((market_price - sale_price) * 100.0 / market_price) AS average_discount  
    -- Average discount percentage
FROM
    bigbasket_products
GROUP BY
    category;



	--Product Price Analysis:
SELECT
    category,
    ROUND(AVG(sale_price), 2) AS average_sale_price,  
	-- Average sale price for each category rounded to 2 decimal places
    MIN(sale_price) AS minimum_sale_price,  
	-- Minimum sale price for each category
    MAX(sale_price) AS maximum_sale_price   
	-- Maximum sale price for each category
FROM
    bigbasket_products
GROUP BY
    category;


-- List the top 10 highest-rated products across all categories.
SELECT TOP 5 product, category
FROM bigbasket_products
ORDER BY rating DESC;

--Discount Analysis:
SELECT category,
  ROUND(AVG((market_price - sale_price) / market_price * 100), 2) 
	AS average_discount_percentage
FROM bigbasket_products
GROUP BY category;


	--Brand Popularity:
SELECT TOP 10 brand,
    COUNT(*) AS product_count
FROM
    bigbasket_products
GROUP BY brand
ORDER BY product_count DESC;



	--Price Discrepancy
	--Identify products where the market price is significantly 
	--higher than the sale price (e.g., by more than 30%).
SELECT TOP 5
    product,
    category,
    sale_price,
    market_price,
    ROUND((market_price - sale_price) / market_price * 100, 2) 
	AS discount_percentage
FROM bigbasket_products
WHERE(market_price - sale_price) / market_price * 100 > 30
ORDER BY discount_percentage DESC;

	--SANYASI NAIDU LALAM
	-- Identify which sub-categories are performing the worst 
	--in terms of sales, to address potential issues or opportunities for improvement.
SELECT TOP 10 sub_category,
    SUM(sale_price) AS total_sales_volume
FROM bigbasket_products
GROUP BY sub_category
ORDER BY total_sales_volume ASC;

	--SANYASI NAIDU LALAM
--Category-wise Revenue
--Calculate the total revenue generated by each category.
SELECT category,
    SUM(sale_price) AS total_revenue
FROM bigbasket_products
GROUP BY category
ORDER BY total_revenue DESC;


--SANYASI NAIDU LALAM
--High Discount Products:
--List the products with a discount percentage greater than 50%.
SELECT TOP 10
    product,
    category,
    sub_category,
    brand,
    ROUND((market_price - sale_price) / market_price * 100, 2) 
	AS discount_percentage
FROM bigbasket_products
ORDER BY discount_percentage DESC;

--Customer Favorite Brands:
--Determine the average rating for each brand.
SELECT TOP 10 brand,
    ROUND(AVG(rating), 2) 
	AS average_rating
FROM bigbasket_products

GROUP BY brand
ORDER BY average_rating DESC;

--Customer Least Favorite Brands:
--Determine the average rating for each brand.
SELECT TOP 10 brand,
    ROUND(AVG(rating), 2) 
	AS average_rating
FROM bigbasket_products
WHERE rating IS NOT NULL
GROUP BY brand
ORDER BY average_rating ASC;



